version: '2.3'
services:
  local:
    container_name: reg-local
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - DELETE_ENABLED=true
    volumes:
      - /data/registry:/var/lib/registry
    ports:
      - 15000:5000
    networks:
      - proxy-net
  gcr:
    container_name: reg-gcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      ##墙外
      ##- PROXY_REMOTE_URL=https://gcr.io
      ##墙内二代
      - PROXY_REMOTE_URL=https://b9pmyelo.mirror.aliyuncs.com
    volumes:
      - /data/registry:/var/lib/registry
    networks:
      - proxy-net
  k8s-gcr:
    container_name: reg-k8s-gcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      ##墙外
      ##- PROXY_REMOTE_URL=https://k8s.gcr.io
      ##墙内二代
      - PROXY_REMOTE_URL=https://registry.cn-hangzhou.aliyuncs.com/google_container
    volumes:
      - /data/registry:/var/lib/registry
    networks:
      - proxy-net
  ui:
    container_name: reg-ui
    image: findsec/registry-ui:latest
    restart: always
    links:
      - local:reg-local
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://reg-local:5000
      - DELETE_IMAGES=true
    networks:
      - proxy-net
  nexus:
    container_name: nexus3
    image: sonatype/nexus3:3.47.1
    restart: always
    ports:
      - 18081:8081
      - 18082:8082
      - 18083:8083
    environment:
      ## NEXUS_CONTEXT: nexus
      INSTALL4J_ADD_VM_PARAMS: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=768m -Djava.util.prefs.userRoot=/nexus-data"
    volumes:
      ## sudo rm -f /data/nexus
      ## sudo mkdir -p /data/nexus
      ## sudo chown -R 200 /data/nexus
      - /data/nexus:/nexus-data
    networks:
      - proxy-net
  nginx:
    container_name: reg-nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - ui:reg-ui
      - gcr:reg-gcr
      - k8s-gcr:reg-k8s-gcr
      - nexus:nexus3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/nginx/ssl
    networks:
      - proxy-net
networks:
  proxy-net:
    external: false
